save tile entity packets too
PrismarineJS/minecraft-chunk-dumper pull request #17
Opened 2021-03-13 07:25 UTC by u9g

I also made gamemode creative default because it's helpful for getting the blocks that you need like signs quickly for testing

2021-03-13 23:38 UTC, rom1504 commented
please rebase

2021-03-13 23:40 UTC, rom1504 requested changes
this module test coverage is pretty much 100%
I actually did TDD here

Let's keep it like this, can you adapt tests ?

2021-03-13 23:48 UTC, u9g commented
> this module test coverage is pretty much 100%
> I actually did TDD here
> 
> Let's keep it like this, can you adapt tests ?

I 

> this module test coverage is pretty much 100%
> I actually did TDD here
> 
> Let's keep it like this, can you adapt tests ?

I can't adapt tests as there are very few naturally spawning block entities, the only way I could think of is if I make a mineflayer bot during continuous saving to use a block entity

2021-03-13 23:49 UTC, u9g commented
> please rebase

done

2021-03-13 23:52 UTC, rom1504 commented
the tests check the existence of files, not their content
you can def do that

2021-03-13 23:53 UTC, u9g commented
> the tests check the existence of files, not their content
> you can def do that

def do what, what if there is no block entities?

2021-03-13 23:56 UTC, rom1504 commented
if there are no block entities there should still be an empty file

but anyway, if there are no block entities, how do you intend to use this ?

2021-03-13 23:57 UTC, u9g commented
> if there are no block entities there should still be an empty file
> 
> but anyway, if there are no block entities, how do you intend to use this ?

It doesnt work like that, it puts a file when the packet happens with the location of the block entity. You use it with continuous capture, by going into the world and doing it yourself (ie: place a sign, use a cauldron, etc)

2021-03-14 00:05 UTC, rom1504 commented
yeah that doesn't make sense with the design of this package
could you please adapt the code so it's more useful ?

https://github.com/PrismarineJS/minecraft-chunk-dumper#usage is the normal use

in particular it's used to dump 10 chunks for a version and add that to pchunk test folder https://github.com/PrismarineJS/prismarine-chunk/tree/master/test

2021-03-14 00:06 UTC, u9g commented
> yeah that doesn't make sense with the design of this package
> 
> could you please adapt the code so it's more useful ?
> 
> 
> 
> https://github.com/PrismarineJS/minecraft-chunk-dumper#usage is the normal use
> 
> 
> 
> in particular it's used to dump 10 chunks for a version and add that to pchunk test folder https://github.com/PrismarineJS/prismarine-chunk/tree/master/test

so how do you suggest I make the block entities get there?

2021-03-14 00:10 UTC, rom1504 commented
same as the rest of the package. You wait for block entities chunks to be as big as what the user asked

2021-03-14 00:12 UTC, rom1504 commented
the end result regardless of the way should be we have N chunks with light, chunk and block entities files
otherwise it won't be possible to use that in pchunk tests

2021-03-14 00:12 UTC, u9g commented
> same as the rest of the package. You wait for block entities chunks to be as big as what the user asked

its not a chunk though, its 1 block that pops up, so do I just keep getting chunks until I collect x number if blocks?

2021-03-14 00:12 UTC, rom1504 commented
yes

2021-03-14 00:13 UTC, rom1504 commented
ah and yeah you're using the wrong packet
tile_entity_data is useful only for old versions

for new versions, block entities are part of the chunk packet

2021-03-14 00:14 UTC, u9g commented
> ah and yeah you're using the wrong packet
> 
> tile_entity_data is useful only for old versions
> 
> 
> 
> for new versions, block entities are part of the chunk packet

so this pr isnt needed since chunk packet is already dumped?

2021-03-14 00:21 UTC, rom1504 commented
no this part of the packet is not dumped currently
and the old packet is still needed for old versions

2021-03-14 00:22 UTC, u9g commented
> no this part of the packet is not dumped currently
> 
> and the old packet is still needed for old versions

what is the old packet, and for what minecraft versions is it?

2021-03-14 00:30 UTC, rom1504 commented
tile_entity_data is the old packet

it's used until 1.15 iirc

2021-03-14 00:31 UTC, u9g commented
thats false, I got this from 1.16.5

2021-03-14 00:36 UTC, rom1504 commented
https://wiki.vg/Protocol#Chunk_Data

tile_entity_data is the update packet, similar to block update one

2021-03-14 00:41 UTC, u9g commented
> https://wiki.vg/Protocol#Chunk_Data
> 
> 
> 
> tile_entity_data is the update packet, similar to block update one

Oh, so instead I should just be fetching that. So again, is this not needed?

2021-03-14 00:53 UTC, rom1504 commented
yes it's needed
https://github.com/PrismarineJS/minecraft-chunk-dumper/blob/62aaf0eb983fb51285d5e9e07b366a772440170e/index.js#L39

2021-06-16 21:08 UTC, rom1504 commented
would be great to finish

2021-07-06 12:31 UTC, rom1504 commented
can you use this to produce data and put it in https://github.com/PrismarineJS/prismarine-chunk/pull/113 ?
last check to make sure it works as expected

2021-07-06 12:32 UTC, rom1504 commented on index.js
> +          }, 100)
1000 no ?

2021-07-06 12:32 UTC, rom1504 commented on index.js
> +        this.client.on('login', () => {
login prob not enough, just wait 1000

2021-07-07 09:23 UTC, rom1504 commented
merged the other one, please fix conflicts

2021-07-10 19:15 UTC, closed without merging