Add support for 1.17
PrismarineJS/minecraft-chunk-dumper pull request #22
Opened 2021-06-17 11:20 UTC by Archengius

Fix crash with CLI parsing version as number

2021-06-18 20:05 UTC, rom1504 requested changes
Why do we need to do this condensing here instead of in pchunk ?

2021-06-19 05:07 UTC, Archengius commented
Because otherwise we would need to completely change dumped chunk format and create 32 lighting files for each chunk. I don't think it's reasonable, and to end up even with 2 files you still need to do the condensing on the dumper side.

2021-06-19 11:57 UTC, rom1504 commented
why not just store the packet fields as they are ? it's all serialized as json anyway https://github.com/PrismarineJS/minecraft-chunk-dumper/blob/2a0b920298e492444c89383a47afefb7a42fbc3e/index.js#L256

the objective of this package is to store the information in a format as raw as possible, so they can serve as test files in pchunk and other packages

if we do some additional preprocessing, then it will need to be duplicated in all user packages, better avoid it

2021-06-19 11:58 UTC, rom1504 commented
if the format changed, it changed, and pchunk/mineflayer will have to adapt anyway

2021-06-21 05:39 UTC, Archengius commented
Removed condensing, hopefully this is an acceptable storage format for lighting

2021-07-01 17:40 UTC, rom1504 commented on index.js
> +function flattenMaskArray (sectionBitMask) {
this is not needed here and introduces boilerplate everywhere if used
prismarine-chunk needs to handle all transformations

2021-07-07 09:22 UTC, rom1504 approved these changes

2021-07-07 09:22 UTC, merged